url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ryan Siegel" # the name of your site, e.g. ACME Corp.
description: "A live Resume and CV"
